services:
  redis:
    image: redis:alpine
    container_name: spend_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d spend'"]
      interval: 10s
      timeout: 3s
      retries: 3
  minio:
    image: minio/minio
    container_name: spend_minio
    ports:
      - "9000:9000"    
      - "9001:9001"    
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  redis_data:
  postgres_data:
  postgres_test_data:
  minio_data:
